version: '2'
services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - /etc/nginx/vhost.d
      - /usr/share/nginx/html
      - /home/ec2-user/pushmyshop-docker/certs:/etc/nginx/certs:ro
    labels:
      - "com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy=true"
    networks:
      - pushmyshop
  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /home/ec2-user/pushmyshop-docker/certs:/etc/nginx/certs:rw
    volumes_from:
      - nginx-proxy
  pushmyshop-api:
    image: pushmyshop/pushmyshop-api:latest
    container_name: pushmyshop-api
    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /tmp/pushmyshop:/tmp/pushmyshop
    expose:
      - 8080
    networks:
      - pushmyshop
  pushmyshop-market:
    image: pushmyshop/pushmyshop-market:latest
    container_name: pushmyshop-market
    networks:
      - pushmyshop
    environment:
      - VIRTUAL_HOST=pushmyshop.com
      - LETSENCRYPT_HOST=pushmyshop.com
      - LETSENCRYPT_EMAIL=contact.pushmyshop@gmail.com
networks:
  pushmyshop:
