version: '2'
services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
  pushmyshop-api:
    image: pushmyshop/pushmyshop-api:latest
    container_name: pushmyshop-api
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp/pushmyshop:/tmp/pushmyshop
      - /usr/local/bin/docker:/usr/bin/docker
    expose:
      - 8080
    environment:
      - VIRTUAL_HOST=pushmyshop-api.com
  pushmyshop-market:
    image: pushmyshop/pushmyshop-market:latest
    container_name: pushmyshop-market
    expose:
      - 8080
    environment:
      - VIRTUAL_HOST=pushmyshop.com
